name = "personal-website"
type = "javascript"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "personal-website"
database_id = "8848e765-afe5-407b-85f8-1b09d5c128e0"

# Serve static files from root directory
[site]
bucket = "."

